### ISSUE TITLE
Question: netstandard2.0 release

### ISSUE THREAD

**Issue by legezam** [markcastle/CaseConverter#1]
Hey! 

Thanks for creating this library. Would it be possible to lower the requirements of this library to `netstandard2.0`? That would make it possible to be included in C# source generators. (this lib comes so natural for source gen like libraries) I downloaded the code, downgraded to `netstandard2.0` and it built fine so i can't think of anything that would prevent us from doing it.

Thanks!

**Comment by markcastle** [comment]
I'm really sorry I didn't see your comment until now.. we can 100% do that (if you still need it)

**Comment by markcastle** [comment]
I've (hopefully) resolved this and made a release that's both .NET STANDARD 2.0 and 2.1
It had been a few years since I updated the project so hopefully I got it right, please let me know otherwise.
The Nuget package is taking a while to get indexed so I'm still waiting to see if its fine or not... again, please let me know.

I went the route of supporting multiple .NET STANDARDS.. 2.0 and 2.1.. hopefully that worked?

**Comment by legezam** [comment]
Hi, Thanks for answering! :) Unfortunately I went with a totally different route with my library so my request is no longer applicable.
